import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowUpRight, CalendarDays, CheckCircle2, CircleDollarSign, Clock3, ShieldAlert, Sparkles, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

const formatDate = (date: Date | null | undefined) => date ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(date)) : "Not scheduled";

function MetricCard({ label, value, detail, tone = "navy", icon: Icon }: { label: string; value: number; detail: string; tone?: "navy" | "gold" | "rose" | "sage"; icon: typeof UsersRound }) {
  const tones = { navy: "bg-[#10213d] text-white", gold: "bg-[#f5d77b] text-[#10213d]", rose: "bg-[#ffe5e0] text-[#9f3323]", sage: "bg-[#dcefe8] text-[#174d3b]" };
  return <Card className="overflow-hidden border-0 shadow-[0_16px_40px_-28px_rgba(15,23,42,0.45)]"><CardContent className={`relative min-h-[156px] p-5 ${tones[tone]}`}><Icon className="absolute right-5 top-5 h-5 w-5 opacity-75" /><p className="text-xs font-semibold uppercase tracking-[0.15em] opacity-70">{label}</p><p className="mt-5 text-4xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs opacity-75">{detail}</p></CardContent></Card>;
}

export default function Home() {
  const { data, isLoading, error } = trpc.operations.dashboard.useQuery();
  const [, setLocation] = useLocation();

  if (isLoading) return <div className="space-y-6"><Skeleton className="h-40 w-full rounded-3xl" /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton className="h-40 rounded-2xl" key={index} />)}</div></div>;
  if (error || !data) return <div className="rounded-3xl border border-rose-200 bg-rose-50 p-8 text-rose-900"><ShieldAlert className="mb-3 h-7 w-7" /><h1 className="text-xl font-semibold">Command Center needs attention</h1><p className="mt-2 text-sm">The dashboard could not load. Please refresh or verify your database connection.</p></div>;

  const { metrics, upcoming, recentAudits, workspace, aiQuota } = data;
  const attention = metrics.pendingApprovals + metrics.failedJobs;
  return <div className="mx-auto max-w-[1480px] space-y-6">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#10213d] px-6 py-7 text-white shadow-[0_24px_60px_-32px_rgba(15,23,42,0.65)] sm:px-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border border-[#f5d77b]/30" /><div className="absolute right-16 top-20 h-24 w-24 rounded-full bg-[#f5d77b]/10 blur-2xl" /><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#f5d77b]"><Sparkles className="h-4 w-4" />Owner command center</div><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Recruitment, running with control.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Monitor every pipeline, review consequential approvals, and keep automation within your policy boundaries.</p></div><div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-3"><div className={`h-2.5 w-2.5 rounded-full ${workspace.emergencyStop ? "bg-rose-400" : "bg-emerald-400"}`} /><div><p className="text-xs font-medium">{workspace.emergencyStop ? "Automation paused" : "Automation controlled"}</p><p className="text-[11px] text-slate-400">Mode: {workspace.automationMode} · {workspace.dailyOutboundLimit}/day</p></div></div></div></section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Active pipeline" value={metrics.activeJobs} detail="Jobs in sourcing, screening, or interviews" icon={UsersRound} /><MetricCard label="Approvals" value={metrics.pendingApprovals} detail="Consequential actions waiting for you" icon={CheckCircle2} tone="gold" /><MetricCard label="Receivables" value={metrics.pendingInvoices} detail="Invoices awaiting payment or review" icon={CircleDollarSign} tone="sage" /><MetricCard label="AI budget" value={aiQuota.used} detail={`${Math.max(0, aiQuota.limit - aiQuota.used)} controlled requests left today`} icon={Sparkles} tone={aiQuota.used >= aiQuota.limit ? "rose" : "navy"} /></section>

    <section className="grid gap-6 xl:grid-cols-[1.35fr_0.65fr]"><Card className="border-slate-200 bg-white shadow-[0_12px_35px_-28px_rgba(15,23,42,0.35)]"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#a47d2c]">Pipeline pulse</p><h2 className="mt-1 text-xl font-semibold text-[#10213d]">Where your attention creates momentum</h2></div><Button variant="outline" onClick={() => setLocation("/exceptions")} className="border-slate-200 bg-white text-[#10213d]">Review queue <ArrowUpRight className="ml-2 h-4 w-4" /></Button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f7f5f0] p-4"><p className="text-2xl font-semibold text-[#10213d]">{metrics.prospects}</p><p className="mt-1 text-xs text-slate-500">Prospects in CRM</p></div><div className="rounded-2xl bg-[#f7f5f0] p-4"><p className="text-2xl font-semibold text-[#10213d]">{metrics.candidates}</p><p className="mt-1 text-xs text-slate-500">Candidate records</p></div><div className="rounded-2xl bg-[#f7f5f0] p-4"><p className="text-2xl font-semibold text-[#10213d]">{aiQuota.used}/{aiQuota.limit}</p><p className="mt-1 text-xs text-slate-500">Enforced AI budget today</p></div></div><div className="mt-6 rounded-2xl border border-slate-100"><div className="border-b border-slate-100 px-4 py-3 text-sm font-semibold text-[#10213d]">Operating guardrails</div><div className="grid divide-y divide-slate-100 sm:grid-cols-2 sm:divide-x sm:divide-y-0"><div className="p-4"><p className="text-sm font-medium">Owner approval required</p><p className="mt-1 text-xs leading-5 text-slate-500">Client onboarding, profile sharing, placement confirmation, and invoice issue remain controlled.</p></div><div className="p-4"><p className="text-sm font-medium">No autonomous final rejection</p><p className="mt-1 text-xs leading-5 text-slate-500">AI can surface evidence and low-confidence signals, but a consequential candidate decision stays with you.</p></div></div></div></CardContent></Card>
      <Card className="border-slate-200 bg-white shadow-[0_12px_35px_-28px_rgba(15,23,42,0.35)]"><CardContent className="p-6"><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#a47d2c]" /><h2 className="text-base font-semibold text-[#10213d]">Upcoming interviews</h2></div><div className="mt-4 space-y-3">{upcoming.length === 0 ? <div className="rounded-2xl bg-[#f7f5f0] p-5 text-sm text-slate-500">No interviews scheduled yet. Create a controlled candidate shortlist first.</div> : upcoming.map(item => <div key={item.id} className="flex items-center justify-between rounded-2xl border border-slate-100 p-4"><div><p className="text-sm font-semibold text-[#10213d]">Interview {item.id.slice(-5)}</p><p className="mt-1 text-xs text-slate-500">{formatDate(item.scheduledAt)} · {item.timezone}</p></div><Badge variant="secondary" className="bg-[#dcefe8] text-[#174d3b]">{item.status.replaceAll("_", " ")}</Badge></div>)}</div></CardContent></Card></section>

    <section className="grid gap-6 xl:grid-cols-[0.7fr_1.3fr]"><Card className="border-slate-200 bg-white"><CardContent className="p-6"><div className="flex items-center justify-between"><h2 className="text-base font-semibold text-[#10213d]">Safety status</h2><ShieldAlert className={`h-5 w-5 ${attention > 0 ? "text-[#d85243]" : "text-emerald-600"}`} /></div><div className="mt-5 space-y-4"><div className="flex justify-between text-sm"><span className="text-slate-500">Queued automation</span><strong className="text-[#10213d]">{metrics.queuedJobs}</strong></div><div className="flex justify-between text-sm"><span className="text-slate-500">Open attention items</span><strong className="text-[#10213d]">{attention}</strong></div><div className="flex justify-between text-sm"><span className="text-slate-500">Outbound control</span><Badge className="bg-[#10213d]">{workspace.automationMode}</Badge></div></div><Button onClick={() => setLocation("/control")} variant="outline" className="mt-6 w-full border-slate-200 bg-white text-[#10213d]">Open control plane</Button></CardContent></Card>
      <Card className="border-slate-200 bg-white"><CardContent className="p-6"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#a47d2c]" /><h2 className="text-base font-semibold text-[#10213d]">Recent audit activity</h2></div><div className="mt-4 divide-y divide-slate-100">{recentAudits.length === 0 ? <p className="py-6 text-sm text-slate-500">Your controlled activity log will appear here as records move through the workflow.</p> : recentAudits.map(event => <div key={event.id} className="flex items-center justify-between gap-4 py-3"><div><p className="text-sm font-medium text-[#10213d]">{event.action.replaceAll(".", " · ")}</p><p className="mt-1 text-xs text-slate-500">{event.resourceType} · {event.createdAt.toLocaleString()}</p></div><Badge variant="outline" className="shrink-0 border-slate-200 text-slate-600">{event.actorType}</Badge></div>)}</div></CardContent></Card></section>
  </div>;
}
